### ISSUE TITLE
Let users edit/delete their activity slot

### ISSUE THREAD

**Issue by TimHeiszwolf** [esrg-knights/Squire#55] opened 2020-08-30 21:46 UTC
Users are currently unable to edit or delete activity slots. This is needed for if they for example make a mistake.

**Comment by EricTRL** [comment] 2022-01-04 13:30
Duplicate of #242 
Closing this in favour of that one, as that one contains a task list of things to change.

**Closed by EricTRL** 2022-01-04 13:30 UTC
Labels: good first issue, feature, activity-registrations
