### ISSUE TITLE
feature/activity slot registration view

### ISSUE THREAD

**Issue by KnightsSecret** [esrg-knights/Squire#82] opened 2020-10-14 11:43 UTC
Hi all,
I have a few requests to make my work as secretary easier:

- Make it possible to view people who have registered for slots with their actual name instead of nickname 
I know this is fixed when I make them a member, but i rather also see the names of non-members if they sign up to activities, since some have found us and our webapp before becoming a Knights member

**Comment by DutcherNL** [comment] 2020-10-14 12:05
Some of the points you make we are already addressing. Currently we got a local run where creating slots is updated a lot in the front end. It will soon be possible to create slots for anybody who is given the right permissions to create slots when slot creation is restricted to administrators. So just in the front end, that should address your time issue as that is removed there.

I've also laid ground work for the ability to indeed alter specefic recurrence instances. I've yet to create all the test cases so we can always confirm it is working though. (recall when I said I'm short on time, that's part of the reason)

Thanks for the other requests :)

**Comment by helaan** [comment] 2020-10-14 12:08
I suggest to split up this issue into multiple issues to make discussion of it easier. Should I split it?

**Comment by helaan** [comment] 2020-10-14 12:34
NOTE: this issue was changed to only contain the first item

Currently we have a few "names" stored in the system: we have the username (I'll take my user as an example, my username is `henk`, many people use their standard handle), we have their first name (which for me is `Henk`, with no last name filled in. For most people this is fairly accurate, but this is optional so some users do not have a first name, while others use it as shitpost territory) and we have the name in the Members file. You can see this overview in the Squire admin panel.

The final entry is most accurate and I believe we currently use Membership name, First name, then Username. I think this order is fine and we should probably make it easier for people to change their own first name, hoping that this crystallizes out. Note that you do not want to change people's usernames in the backend, as that changes their login details.

On the technical side I recommend that we make users able to change their own first/last name and then on the policy side we ask people to switch to their real name. What do the others think?

**Comment by KnightsSecret** [comment] 2020-10-14 12:43
I meant that for me it's really annoying to have this
![image](https://user-images.githubusercontent.com/72865919/95989927-2f026200-0e2b-11eb-8e50-b5bfba438ac8.png)
Cause with only some of them (mjeck, arms, ivbro) i know which people they refer to. Others I have no clue at all.
For instance yesterday I was having trouble figuring out who the other 3 people where who registered for my boardgame slot (in this case diceforge) Also somebody (SpicyGhost, also visible here) registered himself in the non-knights signup slot, therefore I wouldn't even know who he was even if I used the workaround of giving everybody a membership so that name would display (like in this picture Antonie shows instead of airclever)

**Comment by helaan** [comment] 2020-10-14 12:49
I think I have a clue why people are using nicknames: that's how the registration form currently calls the first name field. The field called "nickname" is called "first name" in the database: https://github.com/esrg-knights/Squire/blob/1f1d943c8b48bfde2c0650f616ebdc78737df833/core/forms.py#L65

**Comment by EricTRL** [comment] 2020-10-14 12:52
> On the technical side I recommend that we make users able to change their own first/last name and then on the policy side we ask people to switch to their real name. What do the others think?

We're currently using the first_name field for people's nicknames (which was intentional). The last_name field is currently unused.
We could also ask people for their "real name" upon registration in addition to their nickname. This also means we'd need to look at how we handle this information if someone is a member, as those have already specified their real name (the same issue already exists for email addresses; there's one in the user-model and one in the membership-file model but they don't need to be the same).

**Comment by helaan** [comment] 2020-10-14 12:55
We could underline their nickname with their real name, but I think that as an association we should use real names and get rid of nicknames entirely as the primary way to display someones name

**Comment by DutcherNL** [comment] 2021-07-26 12:18
From what I gather the problem is not in Activity Registrations, but with how we handle naming when logging it which is a different problem. I shall close this and open a new issue that illustrates the problem more clearly.

**Closed by DutcherNL** 2021-07-26 12:18 UTC
Labels: activity-registrations, front-end, user accounts
